In [8]:
import pandas as pd
import os
import pickle
import matplotlib.pyplot as plt

%matplotlib inline

In [9]:
pickle_merged = open(os.path.join(os.getcwd(), '..', 'data', 'processed', 'merged_data.pickle'), 'rb')
data = pickle.load(pickle_merged)
display(data.head())
print(data.shape)

year  income_index  education_index  white_alone  rent_index  \
geoid                                                                       
48021950100  2000  73599.981153         3.617289    86.192698  723.087018   
48021950200  2000  67668.904461         3.154098    67.591995  752.448335   
48021950300  2000  78678.935400         3.669384    81.097069  808.205215   
48021950400  2000  75438.539903         4.075207    76.605317  869.478211   
48021950600  2000  67172.153161         3.465056    88.921283  737.822784   

               value_index   employed  
geoid                                  
48021950100  153375.729370  98.308865  
48021950200  118748.232408  96.715168  
48021950300  178808.676101  97.032326  
48021950400  158917.899778  98.340471  
48021950600  134719.422878  96.891342

(3150, 7)


## Check for missing data by column

In [10]:
has_missing = {}
all_missing = []
for col in data.columns[1:]:
    has_missing[col] = data[data[col] == 0].index.unique().tolist()
    all_missing += has_missing[col]
    print('Missing {}\n\t{}'.format(col, has_missing[col]))
all_missing = list(set(all_missing))
print('\nNumber of tracts with missing data: {}'.format(len(all_missing)))

Missing income_index
	[48453001606, 48453980000, 48453002319]
Missing education_index
	[48453980000]
Missing white_alone
	[48453980000]
Missing rent_index
	[48453001606, 48453980000, 48453002319, 48453001916, 48491020109, 48453001917]
Missing value_index
	[48453001606, 48453980000, 48453002319, 48453000203, 48453000601, 48453001753, 48453001849]
Missing employed
	[48453980000]

Number of tracts with missing data: 10


In [11]:
for geoid in all_missing:
    display(data.loc[geoid])

year  income_index  education_index  white_alone  rent_index  \
geoid                                                                       
48453980000  2000           0.0         0.000000     0.000000         0.0   
48453980000  2009           0.0         0.000000     0.000000         0.0   
48453980000  2010           0.0         0.000000     0.000000         0.0   
48453980000  2011           0.0         2.947368    78.947368         0.0   
48453980000  2012           0.0         2.651934    66.161616         0.0   
48453980000  2013           0.0         2.627027    64.285714         0.0   
48453980000  2014           0.0         2.586735    64.732143         0.0   
48453980000  2015           0.0         0.000000     0.000000         0.0   
48453980000  2016           0.0         0.000000     0.000000         0.0   

             value_index  employed  
geoid                               
48453980000          0.0       0.0  
48453980000          0.0       0.0  
48453980000          0.0       0.0  
48453980000          0.0     100.0  
48453980000          0.0     100.0  
48453980000          0.0     100.0  
48453980000          0.0     100.0  
48453980000          0.0       0.0  
48453980000          0.0       0.0

year  income_index  education_index  white_alone  rent_index  \
geoid                                                                       
48453001606  2000           0.0         1.000000    70.000000         0.0   
48453001606  2009           0.0         1.955949    90.441709         0.0   
48453001606  2010           0.0         1.965011    90.346535         0.0   
48453001606  2011           0.0         2.607143    85.445205         0.0   
48453001606  2012           0.0         2.431635    87.096774         0.0   
48453001606  2013           0.0         2.873188    87.187500         0.0   
48453001606  2014           0.0         3.036697    71.929825         0.0   
48453001606  2015           0.0         3.093750    70.833333         0.0   
48453001606  2016           0.0         2.466667    81.250000         0.0   

             value_index    employed  
geoid                                 
48453001606          0.0  100.000000  
48453001606          0.0   82.186821  
48453001606          0.0   82.178218  
48453001606          0.0   96.840149  
48453001606          0.0   94.700461  
48453001606          0.0   95.000000  
48453001606          0.0  100.000000  
48453001606          0.0  100.000000  
48453001606          0.0  100.000000

year  income_index  education_index  white_alone   rent_index  \
geoid                                                                        
48453000203  2000  62791.471994         4.520231    77.284946  1663.448912   
48453000203  2009  65192.850374         6.002611    82.864137  1745.857691   
48453000203  2010  49401.567518         3.503208    74.722503  1695.356011   
48453000203  2011  57982.768197         5.731629    81.427531  1704.187605   
48453000203  2012  72739.056946         5.545788    84.295912  1708.497296   
48453000203  2013  69500.253260         5.519002    83.745365  1723.312858   
48453000203  2014  67703.978297         5.569318    78.855422  1724.151429   
48453000203  2015  71266.747750         5.795007    83.356164  1783.125588   
48453000203  2016  74707.746479         5.578454    77.210884  1770.845070   

               value_index    employed  
geoid                                   
48453000203  178925.794483  100.000000  
48453000203       0.000000   95.968791  
48453000203       0.000000   97.105943  
48453000203       0.000000   96.727853  
48453000203       0.000000   96.783626  
48453000203       0.000000   93.579902  
48453000203       0.000000   91.225627  
48453000203       0.000000   90.461298  
48453000203       0.000000   91.383056

year   income_index  education_index  white_alone   rent_index  \
geoid                                                                         
48491020109  2000  107433.976617         4.457705    94.191805  1197.653528   
48491020109  2009   98519.886214         4.529985    84.747706   974.220907   
48491020109  2010  127231.845177         4.849755    93.122677     0.000000   
48491020109  2011  136659.007316         4.908183    92.208286     0.000000   
48491020109  2012  127895.272049         4.818722    92.697692  1557.988775   
48491020109  2013  134375.600654         4.962907    92.283298  1534.854124   
48491020109  2014  134665.424275         4.986454    89.993460  1577.932264   
48491020109  2015  142960.987821         5.058797    89.970588  1618.993309   
48491020109  2016  137905.770965         4.963777    92.453901  1667.582418   

               value_index   employed  
geoid                                  
48491020109  246216.050389  98.122066  
48491020109  257269.848834  91.497227  
48491020109  337380.206141  94.005213  
48491020109  316972.902309  95.711593  
48491020109  315210.801784  99.099526  
48491020109  317683.979786  98.214286  
48491020109  334810.670604  96.414687  
48491020109  368726.111969  98.096749  
48491020109  391289.292731  97.194164

year  income_index  education_index  white_alone   rent_index  \
geoid                                                                        
48453001753  2000  95199.011560         5.756381    82.668977  1326.998219   
48453001753  2009  79144.828515         5.659379    68.837593  1095.540446   
48453001753  2010  69946.780345         5.603933    68.210718  1112.458318   
48453001753  2011  71467.836454         5.444444    70.558376  1111.635269   
48453001753  2012  69003.240253         5.305085    78.779841  1091.103171   
48453001753  2013  63284.702567         5.505632    78.591817  1099.235402   
48453001753  2014  64439.985134         5.570755    72.568093  1111.106603   
48453001753  2015  72271.326808         5.707289    75.772201  1179.226751   
48453001753  2016  75401.662050         5.796394    73.746582  1240.778401   

               value_index    employed  
geoid                                   
48453001753  205948.311832  100.000000  
48453001753  181781.408250   97.105263  
48453001753       0.000000   95.845137  
48453001753       0.000000   97.097625  
48453001753       0.000000   96.320755  
48453001753       0.000000   97.058824  
48453001753       0.000000   96.421268  
48453001753       0.000000   94.512195  
48453001753       0.000000   95.339806

year  income_index  education_index  white_alone  rent_index  \
geoid                                                                       
48453002319  2000       0.00000         2.758480    39.572989    0.000000   
48453002319  2009   25169.73345         2.914110    59.099804  811.024744   
48453002319  2010       0.00000         2.914894    56.860321    0.000000   
48453002319  2011       0.00000         2.271523    72.274143    0.000000   
48453002319  2012       0.00000         2.687683    72.708333    0.000000   
48453002319  2013       0.00000         2.712284    68.988764    0.000000   
48453002319  2014       0.00000         2.740708    67.021277    0.000000   
48453002319  2015       0.00000         2.669675    67.667845    0.000000   
48453002319  2016       0.00000         2.801066    62.885217    0.000000   

             value_index    employed  
geoid                                 
48453002319          0.0  100.000000  
48453002319          0.0  100.000000  
48453002319          0.0  100.000000  
48453002319          0.0  100.000000  
48453002319          0.0   75.000000  
48453002319          0.0   66.666667  
48453002319          0.0   69.976359  
48453002319          0.0   70.008834  
48453002319          0.0   70.611880

year  income_index  education_index  white_alone   rent_index  \
geoid                                                                        
48453001849  2000  76187.506861         5.235588    68.948655  1273.658446   
48453001849  2009  70783.758497         5.403065    49.051397  1025.206216   
48453001849  2010  69313.828235         5.336699    55.077976  1029.431600   
48453001849  2011  71942.069580         5.371473    50.663599  1065.219798   
48453001849  2012  71121.151409         5.265649    55.736833  1061.799210   
48453001849  2013  77311.996479         5.146285    52.121992  1083.436354   
48453001849  2014  70502.493012         5.118787    54.148230  1131.305282   
48453001849  2015  70619.465309         5.051558    60.103110  1168.037525   
48453001849  2016  74229.679977         5.128727    63.464338  1198.225423   

               value_index   employed  
geoid                                  
48453001849  156850.534125  98.827117  
48453001849   95085.659700  95.296884  
48453001849   93571.651600  94.491070  
48453001849   90683.812300  94.599121  
48453001849       0.000000  95.703858  
48453001849       0.000000  95.503942  
48453001849       0.000000  92.992972  
48453001849       0.000000  95.201062  
48453001849  102439.024390  96.191845

year  income_index  education_index  white_alone   rent_index  \
geoid                                                                        
48453000601  2000  28188.649310         5.796407    64.807345   681.387356   
48453000601  2009  15664.745267         5.181176    63.095800  1347.243792   
48453000601  2010  14683.551482         4.612836    64.748670  1288.740873   
48453000601  2011  15195.180653         4.225000    67.860569  1349.516899   
48453000601  2012  15660.415383         4.082840    68.818475  1414.919261   
48453000601  2013  14468.222578         3.837093    71.558553  1414.520631   
48453000601  2014  17248.698250         3.611276    71.350442  1280.021544   
48453000601  2015  21752.420924         4.325333    73.151552  1323.428115   
48453000601  2016  24056.748466         4.365385    72.755356  1260.238095   

              value_index   employed  
geoid                                 
48453000601  313701.06825  93.778964  
48453000601       0.00000  84.105176  
48453000601       0.00000  86.096897  
48453000601       0.00000  67.499733  
48453000601       0.00000  71.396275  
48453000601       0.00000  74.898309  
48453000601  633625.65000  78.996634  
48453000601  632897.76250  76.498875  
48453000601  625000.00000  82.501497

year   income_index  education_index  white_alone   rent_index  \
geoid                                                                         
48453001916  2000  216038.217983         5.824662    90.659169  3142.701405   
48453001916  2009  195620.030495         5.974482    86.791333  1897.874673   
48453001916  2010  196777.138330         6.024712    84.197829     0.000000   
48453001916  2011  205971.206893         6.178441    84.873708     0.000000   
48453001916  2012  205590.327169         6.186397    83.289046     0.000000   
48453001916  2013  206959.643539         6.145557    85.965942  1416.788423   
48453001916  2014  220376.900590         6.148981    87.052759  1173.584900   
48453001916  2015  217298.968540         6.046875    87.603559  1554.115617   
48453001916  2016  205592.998955         5.901531    87.936409  1505.434783   

               value_index   employed  
geoid                                  
48453001916  490996.576171  98.869801  
48453001916  597845.356813  96.211154  
48453001916  724128.195215  97.003745  
48453001916  731532.250559  98.018494  
48453001916  710523.553739  98.411257  
48453001916  747896.205138  99.605090  
48453001916  752254.838654  98.998635  
48453001916  674199.104112  98.599187  
48453001916  714371.569704  98.000888

year   income_index  education_index  white_alone   rent_index  \
geoid                                                                         
48453001917  2000  215973.964602         5.828400    90.670616  3153.470306   
48453001917  2009  195383.880823         5.974250    86.793970  1919.238786   
48453001917  2010  189678.307000         6.082844    87.526162  2058.225002   
48453001917  2011  184255.248562         6.151806    89.995669  1963.037819   
48453001917  2012  183381.989274         6.173329    86.740212  1829.380367   
48453001917  2013  185009.204448         6.131389    88.069506  1803.185265   
48453001917  2014  174744.160525         6.023046    87.203112     0.000000   
48453001917  2015  182744.687037         6.035276    87.001003  1717.191082   
48453001917  2016  182827.145466         6.017926    86.767135  1736.986301   

               value_index   employed  
geoid                                  
48453001917  489552.439126  98.867463  
48453001917  597415.476917  96.195965  
48453001917  527763.025210  97.000833  
48453001917  516843.510080  95.897140  
48453001917  501958.066851  95.898161  
48453001917  512095.647266  96.804299  
48453001917  539184.744099  94.693992  
48453001917  564557.422672  94.195323  
48453001917  594412.630890  95.702903

## Missing Data
There are 10 census tracts with missing data (zeros). I'll need to figure out what to do with each of them. There are three census tracts (6 data points total) that have zeros in the rent column. This case arises when there are no properties within the census tract that are being rented at the time of the census/survey. These are pretty straight forward to impute. I'll be using a straight linear interpolation since there's so few missing data points.

### Imputable
*48453001916*: Barton Creek Habitat Preserve to Bee Caves Rd
* No rental properties - 2010, 2011, 2012

*48453001917*: Lost Creek
* No rental properties - 2014

*48491020109*: North of Lake Georgetown
* No rental properties - 2010, 2011

The remaining seven census tracts have missing data in the home value column, which is more troublesome. After digging a bit deeper with GIS and Google Maps, I've found that these tracts have no residential households, so it's no suprise that the home value data is missing. What's surprising is that they actually have some data that's not missing in the home value column. How could this be? [elaborate]

### Tracts to Drop
*48453980000*: Austin Bergstrom Airport
* No population or housing

*48453001606*: Austin State Supported Living Center
* No housing

*48453002319*: Travis County Correctional Complex
* No housing

*48453000203*: Austin State Hospital, Austin School for the Blind, Central Texas Rehabilitation Center, Texas Department of State Health Services
* No housing (some apartments)

*48453001753*: Gateway Shopping Center
* No housing (some apartments)

*48453001849*: J.J. Pickle (University of Texas), The Domain Shopping Center, Industrial Complex
* No housing (some apartments)

*48453000601*: University of Texas, Capital Complex
* No **real** housing (student apartments/dormatories and some faculty housing with hyperinflated value)

In [12]:
#need to drop tracts before imputing because zeros will be filled with nans and interpolated otherwise
to_drop = [48453980000, 48453001606, 48453002319, 48453000203, 48453001753, 48453001849, 48453000601]
data.drop(labels=to_drop, axis=0, inplace=True)

In [13]:
to_impute = [48453001916, 48453001917, 48491020109]
#replace zeros with nans so pandas knows to interpolate them
data.replace(0, pd.np.nan, inplace=True)
for geoid in to_impute:
    #taking advantage of having duplicate index entries here, usually can only use df.at[...]
    #on a single row. df.loc[...] won't work in this situation because of duplicate index entries
    data.at[geoid, 'rent_index'] = data.loc[geoid, 'rent_index'].interpolate(how='linear').values

In [14]:
#now save the cleaned data
pickle_clean = open(os.path.join(os.getcwd(), '..', 'data', 'processed', 'clean_data.pickle'), 'wb')
pickle.dump(data, pickle_clean)